import ROOT

oldfile = ROOT.TFile.Open("/home/jpivarski/Downloads/2011MCNtuples.root")

NGMuons = oldfile.Get("giteda/NGMuons")
NMuons = oldfile.Get("giteda/NMuons")
Nelectrons = oldfile.Get("giteda/Nelectrons")
NGoodGMuons = oldfile.Get("giteda/NGoodGMuons")
NGoodRecMuons = oldfile.Get("giteda/NGoodRecMuons")
NGoodElectron = oldfile.Get("giteda/NGoodElectron")
GMmass = oldfile.Get("giteda/GMmass")
GMmass_extended = oldfile.Get("giteda/GMmass_extended")
GMmass_extended_600 = oldfile.Get("giteda/GMmass_extended_600")
massZto2muon = oldfile.Get("giteda/massZto2muon")
massZto2e = oldfile.Get("giteda/massZto2e")
mZ12_4mu = oldfile.Get("giteda/mZ12_4mu")
mZ34_4mu = oldfile.Get("giteda/mZ34_4mu")
mZ13_4mu = oldfile.Get("giteda/mZ13_4mu")
mZ24_4mu = oldfile.Get("giteda/mZ24_4mu")
mZ14_4mu = oldfile.Get("giteda/mZ14_4mu")
mZ23_4mu = oldfile.Get("giteda/mZ23_4mu")
mZa_4mu = oldfile.Get("giteda/mZa_4mu")
mZb_4mu = oldfile.Get("giteda/mZb_4mu")
mass4mu_7TeV = oldfile.Get("giteda/mass4mu_7TeV")
mass4mu_8TeV = oldfile.Get("giteda/mass4mu_8TeV")
mass4mu_8TeV_low = oldfile.Get("giteda/mass4mu_8TeV_low")
mass4mu_full = oldfile.Get("giteda/mass4mu_full")
mZ12_4e = oldfile.Get("giteda/mZ12_4e")
mZ34_4e = oldfile.Get("giteda/mZ34_4e")
mZ13_4e = oldfile.Get("giteda/mZ13_4e")
mZ24_4e = oldfile.Get("giteda/mZ24_4e")
mZ14_4e = oldfile.Get("giteda/mZ14_4e")
mZ23_4e = oldfile.Get("giteda/mZ23_4e")
mZa_4e = oldfile.Get("giteda/mZa_4e")
mZb_4e = oldfile.Get("giteda/mZb_4e")
mass4e_7TeV = oldfile.Get("giteda/mass4e_7TeV")
mass4e_8TeV = oldfile.Get("giteda/mass4e_8TeV")
mass4e_8TeV_low = oldfile.Get("giteda/mass4e_8TeV_low")
mass4e_full = oldfile.Get("giteda/mass4e_full")
massZmu_2mu2e = oldfile.Get("giteda/massZmu_2mu2e")
massZe_2mu2e = oldfile.Get("giteda/massZe_2mu2e")
mZa_2mu2e = oldfile.Get("giteda/mZa_2mu2e")
mZb_2mu2e = oldfile.Get("giteda/mZb_2mu2e")
mass2mu2e_7TeV = oldfile.Get("giteda/mass2mu2e_7TeV")
mass2mu2e_8TeV = oldfile.Get("giteda/mass2mu2e_8TeV")
mass2mu2e_8TeV_low = oldfile.Get("giteda/mass2mu2e_8TeV_low")
mass2mu2e_full = oldfile.Get("giteda/mass2mu2e_full")
GM_momentum = oldfile.Get("giteda/GM_momentum")
b4_GM_pT = oldfile.Get("giteda/b4_GM_pT")
b4_GM_eta = oldfile.Get("giteda/b4_GM_eta")
GM_phi = oldfile.Get("giteda/GM_phi")
GM_chi2 = oldfile.Get("giteda/GM_chi2")
GM_ndof = oldfile.Get("giteda/GM_ndof")
GM_normchi2 = oldfile.Get("giteda/GM_normchi2")
GM_validhits = oldfile.Get("giteda/GM_validhits")
GM_pixelhits = oldfile.Get("giteda/GM_pixelhits")
after_GM_pT = oldfile.Get("giteda/after_GM_pT")
after_GM_eta = oldfile.Get("giteda/after_GM_eta")
RM_momentum = oldfile.Get("giteda/RM_momentum")
b4_RM_pt = oldfile.Get("giteda/b4_RM_pt")
b4_RM_eta = oldfile.Get("giteda/b4_RM_eta")
RM_phi = oldfile.Get("giteda/RM_phi")
RM_chi2 = oldfile.Get("giteda/RM_chi2")
RM_Ndof = oldfile.Get("giteda/RM_Ndof")
RM_NormChi2 = oldfile.Get("giteda/RM_NormChi2")
RM_goodMuonChamberHit = oldfile.Get("giteda/RM_goodMuonChamberHit")
RM_dxy = oldfile.Get("giteda/RM_dxy")
RM_RelPFIso = oldfile.Get("giteda/RM_RelPFIso")
after_RM_RelPFIso = oldfile.Get("giteda/after_RM_RelPFIso")
RM_validhits = oldfile.Get("giteda/RM_validhits")
RM_pixelhits = oldfile.Get("giteda/RM_pixelhits")
after_RM_pt_Z2mu = oldfile.Get("giteda/after_RM_pt_Z2mu")
after_RM_eta_Z2mu = oldfile.Get("giteda/after_RM_eta_Z2mu")
after_RM_pt = oldfile.Get("giteda/after_RM_pt")
after_RM_eta = oldfile.Get("giteda/after_RM_eta")
after_relPFIso_2mu = oldfile.Get("giteda/after_relPFIso_2mu")
after_relPFIso_2e = oldfile.Get("giteda/after_relPFIso_2e")
after_pt_2mu2e = oldfile.Get("giteda/after_pt_2mu2e")
after_eta_2mu2e = oldfile.Get("giteda/after_eta_2mu2e")
e_momentum = oldfile.Get("giteda/e_momentum")
e_eT = oldfile.Get("giteda/e_eT")
b4_e_pT = oldfile.Get("giteda/b4_e_pT")
b4_e_eta = oldfile.Get("giteda/b4_e_eta")
e_phi = oldfile.Get("giteda/e_phi")
e_SC_eta = oldfile.Get("giteda/e_SC_eta")
e_SC_rawE = oldfile.Get("giteda/e_SC_rawE")
e_RelPFIso = oldfile.Get("giteda/e_RelPFIso")
after_e_RelPFIso = oldfile.Get("giteda/after_e_RelPFIso")
e_RelPFIso_pT = oldfile.Get("giteda/e_RelPFIso_pT")
e_dxy = oldfile.Get("giteda/e_dxy")
after_e_pT_Zto2e = oldfile.Get("giteda/after_e_pT_Zto2e")
after_e_eta_Zto2e = oldfile.Get("giteda/after_e_eta_Zto2e")
after_e_pT = oldfile.Get("giteda/after_e_pT")
after_e_eta = oldfile.Get("giteda/after_e_eta")
after_e_pT_2mu2e = oldfile.Get("giteda/after_e_pT_2mu2e")
after_e_eta_2mu2e = oldfile.Get("giteda/after_e_eta_2mu2e")
SIP3d_mu = oldfile.Get("giteda/SIP3d_mu")
SIP3d_e = oldfile.Get("giteda/SIP3d_e")
e_misshit = oldfile.Get("giteda/e_misshit")

newfile = ROOT.TFile.Open("HiggsZZ4mu_histograms.root", "recreate")
newfile.mkdir("num")
newfile.mkdir("Z")
newfile.mkdir("Z/all")
newfile.mkdir("Z/4mu")
newfile.mkdir("Z/4e")
newfile.mkdir("Z/4mu/by_pt")
newfile.mkdir("Z/4mu/by_mass")
newfile.mkdir("Z/4e/by_pt")
newfile.mkdir("Z/4e/by_mass")
newfile.mkdir("Z/2mu2e")
newfile.mkdir("H")
newfile.mkdir("H/4mu")
newfile.mkdir("H/4e")
newfile.mkdir("H/2mu2e")
newfile.mkdir("muon")
newfile.mkdir("electron")

newfile.cd("num")
NGMuons.SetDirectory(newfile.Get("num")); NGMuons.Write()
NMuons.SetDirectory(newfile.Get("num")); NMuons.Write()
Nelectrons.SetDirectory(newfile.Get("num")); Nelectrons.Write()
NGoodGMuons.SetDirectory(newfile.Get("num")); NGoodGMuons.Write()
NGoodRecMuons.SetDirectory(newfile.Get("num")); NGoodRecMuons.Write()
NGoodElectron.SetDirectory(newfile.Get("num")); NGoodElectron.Write()

newfile.cd("Z/all")
GMmass.SetDirectory(newfile.Get("Z/all")); GMmass.Write()
GMmass_extended.SetDirectory(newfile.Get("Z/all")); GMmass_extended.Write()
GMmass_extended_600.SetDirectory(newfile.Get("Z/all")); GMmass_extended_600.Write()
massZto2muon.SetDirectory(newfile.Get("Z/all")); massZto2muon.Write()
massZto2e.SetDirectory(newfile.Get("Z/all")); massZto2e.Write()

newfile.cd("Z/4mu/by_pt")
mZ12_4mu.SetDirectory(newfile.Get("Z/4mu/by_pt")); mZ12_4mu.Write()
mZ34_4mu.SetDirectory(newfile.Get("Z/4mu/by_pt")); mZ34_4mu.Write()
mZ13_4mu.SetDirectory(newfile.Get("Z/4mu/by_pt")); mZ13_4mu.Write()
mZ24_4mu.SetDirectory(newfile.Get("Z/4mu/by_pt")); mZ24_4mu.Write()
mZ14_4mu.SetDirectory(newfile.Get("Z/4mu/by_pt")); mZ14_4mu.Write()
mZ23_4mu.SetDirectory(newfile.Get("Z/4mu/by_pt")); mZ23_4mu.Write()
newfile.cd("Z/4mu/by_mass")
mZa_4mu.SetDirectory(newfile.Get("Z/4mu/by_mass")); mZa_4mu.Write()
mZb_4mu.SetDirectory(newfile.Get("Z/4mu/by_mass")); mZb_4mu.Write()

newfile.cd("H/4mu")
mass4mu_7TeV.SetDirectory(newfile.Get("H/4mu")); mass4mu_7TeV.Write()
mass4mu_8TeV.SetDirectory(newfile.Get("H/4mu")); mass4mu_8TeV.Write()
mass4mu_8TeV_low.SetDirectory(newfile.Get("H/4mu")); mass4mu_8TeV_low.Write()
mass4mu_full.SetDirectory(newfile.Get("H/4mu")); mass4mu_full.Write()

newfile.cd("Z/4e/by_pt")
mZ12_4e.SetDirectory(newfile.Get("Z/4e/by_pt")); mZ12_4e.Write()
mZ34_4e.SetDirectory(newfile.Get("Z/4e/by_pt")); mZ34_4e.Write()
mZ13_4e.SetDirectory(newfile.Get("Z/4e/by_pt")); mZ13_4e.Write()
mZ24_4e.SetDirectory(newfile.Get("Z/4e/by_pt")); mZ24_4e.Write()
mZ14_4e.SetDirectory(newfile.Get("Z/4e/by_pt")); mZ14_4e.Write()
mZ23_4e.SetDirectory(newfile.Get("Z/4e/by_pt")); mZ23_4e.Write()

newfile.cd("Z/4e/by_mass")
mZa_4e.SetDirectory(newfile.Get("Z/4e/by_mass")); mZa_4e.Write()
mZb_4e.SetDirectory(newfile.Get("Z/4e/by_mass")); mZb_4e.Write()

newfile.cd("H/4e")
mass4e_7TeV.SetDirectory(newfile.Get("H/4e")); mass4e_7TeV.Write()
mass4e_8TeV.SetDirectory(newfile.Get("H/4e")); mass4e_8TeV.Write()
mass4e_8TeV_low.SetDirectory(newfile.Get("H/4e")); mass4e_8TeV_low.Write()
mass4e_full.SetDirectory(newfile.Get("H/4e")); mass4e_full.Write()

newfile.cd("Z/2mu2e")
massZmu_2mu2e.SetDirectory(newfile.Get("Z/2mu2e")); massZmu_2mu2e.Write()
massZe_2mu2e.SetDirectory(newfile.Get("Z/2mu2e")); massZe_2mu2e.Write()

newfile.cd("H/2mu2e")
mZa_2mu2e.SetDirectory(newfile.Get("H/2mu2e")); mZa_2mu2e.Write()
mZb_2mu2e.SetDirectory(newfile.Get("H/2mu2e")); mZb_2mu2e.Write()
mass2mu2e_7TeV.SetDirectory(newfile.Get("H/2mu2e")); mass2mu2e_7TeV.Write()
mass2mu2e_8TeV.SetDirectory(newfile.Get("H/2mu2e")); mass2mu2e_8TeV.Write()
mass2mu2e_8TeV_low.SetDirectory(newfile.Get("H/2mu2e")); mass2mu2e_8TeV_low.Write()
mass2mu2e_full.SetDirectory(newfile.Get("H/2mu2e")); mass2mu2e_full.Write()

newfile.cd("muon")
GM_momentum.SetDirectory(newfile.Get("muon")); GM_momentum.Write()
b4_GM_pT.SetDirectory(newfile.Get("muon")); b4_GM_pT.Write()
b4_GM_eta.SetDirectory(newfile.Get("muon")); b4_GM_eta.Write()
GM_phi.SetDirectory(newfile.Get("muon")); GM_phi.Write()
GM_chi2.SetDirectory(newfile.Get("muon")); GM_chi2.Write()
GM_ndof.SetDirectory(newfile.Get("muon")); GM_ndof.Write()
GM_normchi2.SetDirectory(newfile.Get("muon")); GM_normchi2.Write()
GM_validhits.SetDirectory(newfile.Get("muon")); GM_validhits.Write()
GM_pixelhits.SetDirectory(newfile.Get("muon")); GM_pixelhits.Write()
after_GM_pT.SetDirectory(newfile.Get("muon")); after_GM_pT.Write()
after_GM_eta.SetDirectory(newfile.Get("muon")); after_GM_eta.Write()
RM_momentum.SetDirectory(newfile.Get("muon")); RM_momentum.Write()
b4_RM_pt.SetDirectory(newfile.Get("muon")); b4_RM_pt.Write()
b4_RM_eta.SetDirectory(newfile.Get("muon")); b4_RM_eta.Write()
RM_phi.SetDirectory(newfile.Get("muon")); RM_phi.Write()
RM_chi2.SetDirectory(newfile.Get("muon")); RM_chi2.Write()
RM_Ndof.SetDirectory(newfile.Get("muon")); RM_Ndof.Write()
RM_NormChi2.SetDirectory(newfile.Get("muon")); RM_NormChi2.Write()
RM_goodMuonChamberHit.SetDirectory(newfile.Get("muon")); RM_goodMuonChamberHit.Write()
RM_dxy.SetDirectory(newfile.Get("muon")); RM_dxy.Write()
RM_RelPFIso.SetDirectory(newfile.Get("muon")); RM_RelPFIso.Write()
after_RM_RelPFIso.SetDirectory(newfile.Get("muon")); after_RM_RelPFIso.Write()
RM_validhits.SetDirectory(newfile.Get("muon")); RM_validhits.Write()
RM_pixelhits.SetDirectory(newfile.Get("muon")); RM_pixelhits.Write()
after_RM_pt_Z2mu.SetDirectory(newfile.Get("muon")); after_RM_pt_Z2mu.Write()
after_RM_eta_Z2mu.SetDirectory(newfile.Get("muon")); after_RM_eta_Z2mu.Write()
after_RM_pt.SetDirectory(newfile.Get("muon")); after_RM_pt.Write()
after_RM_eta.SetDirectory(newfile.Get("muon")); after_RM_eta.Write()
after_relPFIso_2mu.SetDirectory(newfile.Get("muon")); after_relPFIso_2mu.Write()
after_relPFIso_2e.SetDirectory(newfile.Get("muon")); after_relPFIso_2e.Write()
after_pt_2mu2e.SetDirectory(newfile.Get("muon")); after_pt_2mu2e.Write()
after_eta_2mu2e.SetDirectory(newfile.Get("muon")); after_eta_2mu2e.Write()

newfile.cd("electron")
e_momentum.SetDirectory(newfile.Get("electron")); e_momentum.Write()
e_eT.SetDirectory(newfile.Get("electron")); e_eT.Write()
b4_e_pT.SetDirectory(newfile.Get("electron")); b4_e_pT.Write()
b4_e_eta.SetDirectory(newfile.Get("electron")); b4_e_eta.Write()
e_phi.SetDirectory(newfile.Get("electron")); e_phi.Write()
e_SC_eta.SetDirectory(newfile.Get("electron")); e_SC_eta.Write()
e_SC_rawE.SetDirectory(newfile.Get("electron")); e_SC_rawE.Write()
e_RelPFIso.SetDirectory(newfile.Get("electron")); e_RelPFIso.Write()
after_e_RelPFIso.SetDirectory(newfile.Get("electron")); after_e_RelPFIso.Write()
e_RelPFIso_pT.SetDirectory(newfile.Get("electron")); e_RelPFIso_pT.Write()
e_dxy.SetDirectory(newfile.Get("electron")); e_dxy.Write()
after_e_pT_Zto2e.SetDirectory(newfile.Get("electron")); after_e_pT_Zto2e.Write()
after_e_eta_Zto2e.SetDirectory(newfile.Get("electron")); after_e_eta_Zto2e.Write()
after_e_pT.SetDirectory(newfile.Get("electron")); after_e_pT.Write()
after_e_eta.SetDirectory(newfile.Get("electron")); after_e_eta.Write()
after_e_pT_2mu2e.SetDirectory(newfile.Get("electron")); after_e_pT_2mu2e.Write()
after_e_eta_2mu2e.SetDirectory(newfile.Get("electron")); after_e_eta_2mu2e.Write()
SIP3d_mu.SetDirectory(newfile.Get("electron")); SIP3d_mu.Write()
SIP3d_e.SetDirectory(newfile.Get("electron")); SIP3d_e.Write()
e_misshit.SetDirectory(newfile.Get("electron")); e_misshit.Write()

newfile.Close()
